---
- name: copy alertmanager config
  template:
    force: true
    src: "{{ alertmanager_config_file }}"
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: alertmanager
    group: alertmanager
    mode: 0644
    validate: "/usr/local/bin/amtool --alertmanager.url=  check-config %s"
  notify:
    - restart alertmanager

- name: create systemd service unit
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertmanager
  when: ansible_service_mgr == "systemd"

- name: create openrc service unit
  template:
    src: alertmanager.initd.j2
    dest: /etc/init.d/alertmanager
    owner: root
    group: root
    mode: 0755
  notify:
    - restart alertmanager
  when: ansible_service_mgr == "openrc"

- name: copy alertmanager template files
  copy:
    src: "{{ item }}"
    dest: "{{ alertmanager_config_dir }}/templates/"
    force: true
    owner: alertmanager
    group: alertmanager
    mode: 0644
  with_fileglob: "{{ alertmanager_template_files }}"
